#!/bin/bash

echo ""
for app in $(flatpak list --app --columns=application | awk '{print $1}'); do
    echo "Creating /usr/bin/$app with the content:"
    printf "#!/bin/bash\nflatpak run %s$app\n" | sudo tee "/usr/bin/$app"
    sudo chmod +x "/usr/bin/$app"
    echo ""
done
