#!/bin/bash

unset -v branch
unset -v message

while getopts b:m: p
    do
        case "${p}" in
            b) branch="${OPTARG}";;
            m) message="${OPTARG}";;
            *) echo "Usage: reset_commit -b '<name_of_the_branch_to_push_to>' -m '<commit_message>'"
        esac
done

if [[ -z "$branch" ]] || [[ -z "$message" ]]; then
    echo "Usage: reset_commit -b '<name_of_the_branch_to_push_to>' -m '<commit_message>'"
    exit 1
fi

# Checkout to an orphan branch
git checkout --orphan latest_branch
    
# Add all the files
git add -A
    
# Commit the changes
git commit -m "$message"
    
# Delete the master/main branch
git branch -D "$branch"
    
# Rename the current branch to master/main
git branch -m "$branch"
    
# Force update your repository
git push -f origin "$branch"
