#!/bin/bash

if [[ $(pgrep -c videowall ) -gt 1 ]]; then
    pgrep --oldest videowall | xargs kill -9
fi

video=""
limit=""
quit=""
while getopts p:l:q opt; do
        case "${opt}" in
            p) video="${OPTARG}";;
            l) limit="${OPTARG}";;
            q) quit="True";;
            *) echo "Usage: videowall [-p '<video>' -l '<limit_in_seconds>']" && exit 1
        esac
done

if [[ -n $quit ]]; then pgrep videowall | xargs kill -9; fi

if [[ $video ]]; then
    echo "Preparing video..."
    rm -rf "$HOME/.videowall" && mkdir -p "$HOME/.videowall"
    if [[ -z "$limit" ]]; then
        ffmpeg -y -ss "00:00:00.000" -i "${video}" "$HOME/.videowall/%d.jpg" > /dev/null 2>&1
    else
        ffmpeg -y -ss "00:00:00.000" -t "${limit}" -i "${video}" "$HOME/.videowall/%d.jpg" > /dev/null 2>&1
    fi
    echo "Done!"
fi

if [[ -d "$HOME/.videowall" ]]; then
    iterator=1
    (while true ; do
        hsetroot -cover "$HOME/.videowall/${iterator}.jpg" > /dev/null 2>&1
        iterator=$((iterator + 1))
        if [[ ! -e "$HOME/.videowall/${iterator}.jpg" ]]; then iterator=1; fi
    done) & disown
else
    echo "Prepare a video first!"
fi
